source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.5'
gem 'sinatra-contrib'
gem 'httpclient', '~> 2.4'
gem 'unicorn'
gem "rake", "~> 10.3", ">=10.3.1"
gem "rake-compiler"

group :test do
  gem "minitest-reporters"
  gem "simplecov"
end
