require "rake/testtask"
require 'rake/extensiontask'

Rake::TestTask.new do |t|
  t.libs << "spec"
  t.pattern = "spec/**/*_spec.rb"
  t.warning = false
  t.verbose = true
end

task :default => :test

desc "Generates a coverage report"
task :coverage do
  ENV['COVERAGE'] = "true"
  Rake::Task["test"].execute
end


Rake::ExtensionTask.new do |ext|
  ext.name = 'ruby_cryptopp'
  ext.ext_dir = 'lib/learning_studio_authentication/ext/'
  ext.lib_dir = 'lib/learning_studio_authentication'
end
